In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from css_proj.preprocess.cure_data import get_tweet_info, get_empty_df_cure, get_df_cure
from css_proj.preprocess.utils import initialize_api

In [3]:
api = initialize_api()

In [4]:
%cd ../

/home/harshapk/Projects/CSS_Project

In [7]:
df = get_empty_df_cure()
df.head()

,tweet_id,label,state,tweet_text,retweets,likes,created,lang,device,user_id,user_name,user_handle,user_location,user_description,user_following,user_followers,user_verified,user_total_tweets,user_total_likes,user_total_lists
0,1238288071050706944,0,1,People who drink Arrowhead water on a daily ba...,0,8,2020-03-13 02:17:37+00:00,en,Twitter for iPhone,43567150,Majd Misleh,MajdMisleh,,,59,235,False,23836,40638,0
1,1243032337924972546,0,1,people who drink tin sausage water are immune ...,1,1,2020-03-26 04:29:38+00:00,en,Twitter Web App,66214451,kathryn's üÖøÔ∏èeak,itsleahcar,üáØüá≤,May or may not know how to use a camera.,1211,1500,False,79213,36796,13
2,1236722713424801798,0,1,People who drink water out of the water hose a...,0,0,2020-03-08 18:37:26+00:00,en,Twitter for Android,749253101262024704,Ray Ray,ItsCaizen,"Louisiana, USA","Information Security Analyst, Army National Gu...",23,14,False,200,91,0
3,1231359858894606336,0,0,,0,0,,,,0,,,,,0,0,0,0,0,0
4,1248464260646068224,0,0,,0,0,,,,0,,,,,0,0,0,0,0,0

In [6]:
df = get_df_cure(api, start_idx=0)

  0%|          | 3/2400 [01:00<13:24:31, 20.14s/it]

Failed to get tweet 1231359858894606336 at index 3
Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=60)
Rate limit exceeded at index 3
Try again later

In [8]:
df.iloc[900:930]

,tweet_id,label,state,tweet_text,retweets,likes,created,lang,device,user_id,user_name,user_handle,user_location,user_description,user_following,user_followers,user_verified,user_total_tweets,user_total_likes,user_total_lists
900,1262758662331748353,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
901,1239860966868652032,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
902,1262659145641025536,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
903,1253382462434091009,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
904,1239943437895512066,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
905,1238386024000167936,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
906,1248692639735709696,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
907,1249851162477633537,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
908,1238400415709802497,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
909,1235078378811731971,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
910,1253901218419806209,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
911,1238636960702332928,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
912,1247745180825825282,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
913,1239220144842215425,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
914,1242440586348683266,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
915,1238886023305867266,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
916,1238833646326276096,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
917,1247460662994800643,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
918,1243446899220324352,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
919,1254789947308953602,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
920,1244505960917258240,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
921,1239404120827547648,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
922,1239958658353713158,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
923,1254541637612691456,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
924,1243676835717791747,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
925,1237270044372942848,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
926,1238893570678915072,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
927,1249968437423677440,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
928,1238951527626289152,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0
929,1237438260441382917,1,0,,0,0,,,,0,,,,,0,0,0,0,0,0